### ISSUE TITLE
imaplib.error: SEARCH command error: BAD [b'Parse Error (took 0 ms)']

### ISSUE THREAD

**Issue by mupciamkotki** [dtomlinson91/easy-email-downloader#1]
I wish I could use your script, on the default example getting this error

Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    downloaded_emails = download_emails(
  File "C:\Users\youngfifinascar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\easy_email_downloader\utils.py", line 51, in download_emails
    _, messages = imap.search(None, _search_filter)
  File "C:\Users\youngfifinascar\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 725, in search
    typ, dat = self._simple_command(name, *criteria)
  File "C:\Users\youngfifinascar\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Users\youngfifinascar\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 1030, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: SEARCH command error: BAD [b'Parse Error (took 0 ms)']

using an iCloud mailbox
https://github.com/paperless-ngx/paperless-ngx/issues/2037 
similar error here

**Comment by dtomlinson91** [comment]
Is this Windows 10? Did you install with pip? I tested this on Mac & Linux but not Windows, I can take a look tomorrow, I have an iCloud account I can test with

**Comment by mupciamkotki** [comment]
yep on windows 10 in Parallels, I installed with Poetry, I will test on mac tho

& thanks a lot :3 
edit: all installation methods end with the same outcome on mac
edit2: actually when installing with poetry i get module not found error
edit3: getting this error with my gmail mailbox
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: SEARCH command error: BAD [b'Could not parse command']

**Comment by mupciamkotki** [comment]
Id love some help on that still
